# Generated by Django 5.2.6 on 2025-09-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/cards/')),
                ('title', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/hero/')),
                ('title1', models.CharField(max_length=255)),
                ('paragraph1', models.TextField()),
                ('title2', models.CharField(blank=True, max_length=255, null=True)),
                ('paragraph2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSplitSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(upload_to='about/split/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='petstore.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='petstore.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('coupon_code', models.CharField(blank=True, max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('importer_name', models.CharField(blank=True, max_length=100)),
                ('importer_address', models.TextField(blank=True)),
                ('per_gram_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstore.category')),
                ('additional_images', models.ManyToManyField(blank=True, to='petstore.productimage')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petstore.subcategory')),
                ('subitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petstore.subitem')),
            ],
        ),
    ]
