# Generated by Django 5.2.6 on 2025-09-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0002_aboutcard_abouthero_aboutsplitsection_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcard',
            name='title',
        ),
        migrations.AlterField(
            model_name='aboutcard',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
