# Generated by Django 5.2.6 on 2025-09-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0003_remove_aboutcard_title_alter_aboutcard_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopByPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_by_pet/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
