# Generated by Django 5.2.6 on 2025-09-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0004_shopbypet'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbypet',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
