# Generated by Django 5.2.6 on 2025-09-25 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0005_shopbypet_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetServiceHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_image', models.ImageField(upload_to='petservice/hero/')),
                ('right_image', models.ImageField(upload_to='petservice/hero/')),
                ('logo', models.ImageField(upload_to='petservice/hero/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('customer_service_text', models.CharField(default='Customer Service', max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PetServiceSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory/'),
        ),
        migrations.AddField(
            model_name='subitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subitem/'),
        ),
        migrations.CreateModel(
            name='PetServiceHeroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='petservice/hero/icons/')),
                ('label', models.CharField(max_length=100)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='petstore.petservicehero')),
            ],
        ),
        migrations.CreateModel(
            name='PetServiceColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='petservice/columns/')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='petstore.petservicesection')),
            ],
        ),
    ]
