# Generated by Django 5.2.6 on 2025-09-25 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0007_browsetopic_contactheader_contactinfo_quicklink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageDealSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='homepage/deal/')),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HomepagePromoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.URLField()),
                ('image', models.ImageField(upload_to='homepage/promo/')),
                ('discount_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='homepage/services/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Product Description', max_length=255)),
                ('title1', models.CharField(blank=True, max_length=255)),
                ('paragraph1', models.TextField(blank=True)),
                ('title2', models.CharField(blank=True, max_length=255)),
                ('paragraph2', models.TextField(blank=True)),
                ('title3', models.CharField(blank=True, max_length=255)),
                ('paragraph3', models.TextField(blank=True)),
                ('title4', models.CharField(blank=True, max_length=255)),
                ('paragraph4', models.TextField(blank=True)),
                ('title5', models.CharField(blank=True, max_length=255)),
                ('paragraph5', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_details/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='petstore.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='petstore.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
