# Generated by Django 5.2.6 on 2025-09-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0009_alter_homepagedealsection_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petservicespecial',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
