# Generated by Django 5.2.6 on 2025-09-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0010_alter_petservicespecial_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultVetCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='consultvet/cards/')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Consult Vet Card',
                'verbose_name_plural': 'Consult Vet Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConsultVetHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='consultvet/hero/')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(default='Consult Now', max_length=100)),
                ('button_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consult Vet Hero',
                'verbose_name_plural': 'Consult Vet Hero',
            },
        ),
        migrations.CreateModel(
            name='ConsultVetHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='consultvet/highlight/')),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Consult Now', max_length=100)),
                ('button_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consult Vet Highlight',
                'verbose_name_plural': 'Consult Vet Highlight',
            },
        ),
        migrations.CreateModel(
            name='ConsultVetInfoBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='consultvet/infobar/')),
                ('text', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Consult Vet Info Bar',
                'verbose_name_plural': 'Consult Vet Info Bar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConsultVetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='consultvet/services/')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Consult Vet Service',
                'verbose_name_plural': 'Consult Vet Services',
                'ordering': ['order'],
            },
        ),
    ]
